### ISSUE TITLE
Add Retrofit

### ISSUE THREAD

**Issue by StefanDeBruijn** [RoySuttieKLM/DnDWiki#13]
Setup a real network layer with Retrofit: 
- https://square.github.io/retrofit/
- https://github.com/square/retrofit

The examples on the website seem to be focussed on Java, so perhaps find an article about using it in kotlin if you get stuck, but to get you going the biggest difference will be the simplified signature of the interface methods. Per example:

```
    @GET("someurl/info")
    suspend fun getInfo(): List<Info>
```

**Comment by RoySuttieKLM** [comment]
Merged into main
